// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpiL8MrrMnNrsFedHgBFjHBoqIbKroWq8',
    appId: '1:466511561587:web:fce242b7c5b224faa03b06',
    messagingSenderId: '466511561587',
    projectId: 'silica-operations',
    authDomain: 'silica-operations.firebaseapp.com',
    storageBucket: 'silica-operations.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbbb1fxuFq38KcksCES0VT6cas-Mnbhw',
    appId: '1:466511561587:android:d8d49e64a3b92ee1a03b06',
    messagingSenderId: '466511561587',
    projectId: 'silica-operations',
    storageBucket: 'silica-operations.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0MYQRsYLo1O_Rj_SWXpWHawiENbuZWFM',
    appId: '1:466511561587:ios:d77b61f84570e4eca03b06',
    messagingSenderId: '466511561587',
    projectId: 'silica-operations',
    storageBucket: 'silica-operations.firebasestorage.app',
    iosBundleId: 'com.silica.erp',
  );
}
