import { equipment, auxiliaryConnectedKw } from "./data/equipment.js";
import { componentInventory, processPresets } from "./data/component-inventory.js";
import { createPlantScene } from "./scene/plant-scene.js";
import { simulatePlant } from "./simulation/plant-model.js";
import { planMeshTrain, recommendScreenAdjustments, simulateProductBand } from "./simulation/particle-model.js";

const $=selector=>document.querySelector(selector); const format=(value,digits=1)=>Number(value).toFixed(digits);
const scene=createPlantScene($("#plant-canvas"),equipment,item=>{$("#selected-machine").innerHTML=`<strong>${item.id} · ${item.name}</strong><span>${item.duty} · ${item.motorKw?`${item.motorKw} kW`:"No direct drive"}</span>`;});
function inputs(){return{feedRateTph:Number($("#feed").value),feedSilicaFraction:Number($("#grade").value)/100,massRecovery:Number($("#mass-recovery").value)/100,processWaterM3PerT:Number($("#water-rate").value),waterRecycleFraction:Number($("#recycle").value)/100};}
function row(title,formula,substitution,result,note){return `<article><div><h3>${title}</h3><p>${note}</p></div><div class="formula"><code>${formula}</code><span>${substitution}</span><strong>${result}</strong></div></article>`;}
function renderCalculations(r){const i=inputs();$("#calculation-list").innerHTML=[
  row("Dry product","P = F × Rm",`${format(i.feedRateTph)} × ${format(i.massRecovery,3)}`,`${format(r.productDryTph)} t/h`,"Feed multiplied by total plant mass recovery."),
  row("Product silica grade","Gp = (F × Gf × Rs) ÷ P",`(${format(i.feedRateTph)} × ${format(i.feedSilicaFraction,3)} × 0.893) ÷ ${format(r.productDryTph)}`,`${format(r.productSilicaFraction*100,2)}% SiO2`,"Silica recovery is a calibration assumption and must come from test work."),
  row("Circulating process water","Qw = F × W",`${format(i.feedRateTph)} × ${format(i.processWaterM3PerT)}`,`${format(r.processWaterM3h)} m³/h`,"Base water intensity covers washing, slurry transport and classification."),
  row("Fresh make-up water","Qf = Qw × (1 − Recycle)",`${format(r.processWaterM3h)} × (1 − ${format(i.waterRecycleFraction,2)})`,`${format(r.freshWaterM3h)} m³/h`,"Does not yet include evaporation, leakage or filter-cake losses separately."),
  row("Cyclone pump shaft power","P = ρgQH ÷ η",`1350 × 9.81 × (${format(r.cycloneFlowM3h)} ÷ 3600) × 28 ÷ 0.62`,`${format(r.cyclonePump.shaftKw)} kW → ${format(r.cyclonePump.motorKw,0)} kW motor`,"Preliminary duty uses 28 m TDH, 1.35 t/m³ slurry and 62% pump efficiency."),
  row("Recycle-water pump","P = ρgQH ÷ η",`1030 × 9.81 × (${format(r.recycledWaterM3h)} ÷ 3600) × 22 ÷ 0.70`,`${format(r.recyclePump.shaftKw)} kW → ${format(r.recyclePump.motorKw,0)} kW motor`,"Motor is rounded up after a 15% sizing margin."),
  row("Plant operating demand","Po = Σ(rated kW × utilization)",`Drives + pump shaft duties at ${format(i.feedRateTph)} t/h`,`${format(r.operatingPowerKw)} kW`,`Equivalent to ${format(r.specificPowerKwhT,2)} kWh per tonne of dry feed.`)
].join("");}
function update(){const i=inputs(),r=simulatePlant(i);$("#feed-output").value=format(i.feedRateTph,0);$("#grade-output").value=format(i.feedSilicaFraction*100);$("#mass-recovery-output").value=format(i.massRecovery*100);$("#water-rate-output").value=format(i.processWaterM3PerT);$("#recycle-output").value=format(i.waterRecycleFraction*100,0);$("#product").textContent=`${format(r.productDryTph)} t/h`;$("#product-grade").textContent=`${format(r.productSilicaFraction*100,2)}%`;$("#fresh-water").textContent=`${format(r.freshWaterM3h)} m³/h`;$("#operating-power").textContent=`${format(r.operatingPowerKw)} kW`;const w=$("#capacity-warning");w.hidden=i.feedRateTph<=55;w.textContent=`At ${format(i.feedRateTph,0)} t/h, the concept is above its normal duty. Confirm screen, scrubber, cyclone and magnetic-separator capacity.`;renderCalculations(r);if($("#product-band"))renderSizing();}
equipment.forEach(item=>{$("#equipment-body").insertAdjacentHTML("beforeend",`<tr><td><button class="tag" type="button">${item.id}</button></td><td>${item.name}</td><td>${item.duty}</td><td>${item.motorKw?`${item.motorKw} kW`:"—"}</td><td>${item.speed}</td><td>${item.load}</td></tr>`);});
$("#connected-power").textContent=`${format(equipment.reduce((sum,item)=>sum+item.motorKw,auxiliaryConnectedKw),1)} kW`;

const categories=[...new Set(componentInventory.map(item=>item.category))];
categories.forEach(category=>$("#category").insertAdjacentHTML("beforeend",`<option>${category}</option>`));
Object.keys(processPresets).forEach(name=>$("#preset").insertAdjacentHTML("beforeend",`<option>${name}</option>`));
let selectedSequence=[];

function renderInventory(){const category=$("#category").value;$("#inventory-list").innerHTML=componentInventory.filter(item=>category==="all"||item.category===category).map(item=>`<article><div><span>${item.category}</span><h3>${item.name}</h3><p>${item.function}</p><small>${item.parts.join(" · ")}</small></div><button class="add-component" type="button" data-component="${item.id}">Add</button></article>`).join("");document.querySelectorAll(".add-component").forEach(button=>button.addEventListener("click",()=>{selectedSequence.push(button.dataset.component);renderSequence();}));}

function renderSequence(){const list=$("#process-sequence");list.innerHTML=selectedSequence.map((id,index)=>{const item=componentInventory.find(entry=>entry.id===id);const inlet=item.ports.filter(port=>port.endsWith("-in"))[0]||item.ports[0],outlets=item.ports.filter(port=>port.endsWith("-out"));return `<li><span class="sequence-index">${index+1}</span><div><strong>${item.name}</strong><small>IN: ${inlet} · OUT: ${outlets.join(", ")||"none"}</small></div><button type="button" data-remove="${index}" title="Remove component">×</button></li>`;}).join("");$("#sequence-empty").hidden=selectedSequence.length>0;document.querySelectorAll("[data-remove]").forEach(button=>button.addEventListener("click",()=>{selectedSequence.splice(Number(button.dataset.remove),1);renderSequence();}));}

function renderSizing(){const result=simulateProductBand($("#product-band").value,Number($("#feed").value));$("#band-aperture").textContent=`${result.fineMicron}–${result.coarseMicron} µm`;$("#band-product").textContent=`${format(result.productTph)} t/h`;$("#band-afs").textContent=format(result.afsGfn,1);$("#stream-feed").textContent=`${format(Number($("#feed").value))} t/h solids + wash water`;$("#stream-product").textContent=`${format(result.productTph)} t/h · ${result.bandName} · ${format(result.centerMicron,0)} µm geometric mean`;$("#stream-reject").textContent=`${format(result.rejectTph)} t/h to re-screening, alternate products or reject`;$("#sieve-body").innerHTML=result.retained.map(row=>`<tr><td>${row.aperture?`${row.aperture} µm`:"Pan"}</td><td>${format(row.percent,2)}%</td><td><span class="distribution-bar" style="--value:${Math.max(row.percent,1)}%"></span></td></tr>`).join("");}

function calibrate(){const result=recommendScreenAdjustments({actualAfs:Number($("#actual-afs").value),targetAfs:Number($("#target-afs").value),actualRateTph:Number($("#actual-rate").value),designRateTph:Number($("#feed").value)});$("#calibration-result").innerHTML=`<strong>${result.direction==="finer"?"Shift product finer":result.direction==="coarser"?"Shift product coarser":"Hold current cut"}</strong><span>Target minus actual AFS: ${format(result.difference,1)}</span><ul>${result.recommendations.map(item=>`<li>${item}</li>`).join("")}</ul>`;}

function renderMeshPlan(){const selected=[...document.querySelectorAll(".product-checks input:checked")].map(input=>input.value);const target=$("#mesh-plan-result");if(!selected.length){target.innerHTML="<strong>Select at least one product band.</strong>";return;}const plan=planMeshTrain(selected);target.innerHTML=`<div class="mesh-plan-heading"><strong>${plan.machineCount} boundary screens required</strong><span>Fine-to-coarse oversize cascade</span></div><ol>${plan.stages.map(stage=>`<li><b>R${stage.stage}</b><strong>${stage.meshNumber} mesh</strong><span>${stage.apertureMicron?`${stage.apertureMicron} µm nominal · `:""}through: ${stage.through} · oversize: ${stage.oversize}</span></li>`).join("")}</ol>${plan.warnings.length?`<div class="mesh-warnings">${plan.warnings.map(item=>`<p>${item}</p>`).join("")}</div>`:""}<small>Confirm nominal apertures against the selected ASTM/BS/IS screen-cloth certificate before procurement.</small>`;scene.setMeshTrain(plan.stages);$("#plant-canvas").dataset.rotaryStages=String(plan.machineCount);$("#scene-area").value="rotary";scene.setArea("rotary");}

$("#category").addEventListener("change",renderInventory);$("#load-preset").addEventListener("click",()=>{selectedSequence=[...processPresets[$("#preset").value]];renderSequence();});$("#clear-sequence").addEventListener("click",()=>{selectedSequence=[];renderSequence();});$("#product-band").addEventListener("change",renderSizing);$("#calibrate").addEventListener("click",calibrate);$("#plan-mesh").addEventListener("click",renderMeshPlan);
document.querySelectorAll("input[type=range]").forEach(control=>control.addEventListener("input",update));
document.querySelectorAll(".tabs button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".tabs button").forEach(tab=>tab.classList.toggle("active",tab===button));document.querySelectorAll(".view").forEach(view=>view.classList.toggle("active",view.id===`${button.dataset.view}-view`));}));
let running=true;$("#run-toggle").addEventListener("click",event=>{running=!running;scene.setRunning(running);event.currentTarget.textContent=running?"Pause flow":"Run flow";event.currentTarget.setAttribute("aria-pressed",String(running));});$("#reset-camera").addEventListener("click",()=>scene.resetCamera());
$("#scene-area").addEventListener("change",event=>scene.setArea(event.currentTarget.value));
$("#selected-machine").innerHTML="<strong>Select any machine</strong><span>Its duty, drive and process role will appear here.</span>";renderInventory();renderSequence();renderSizing();renderMeshPlan();calibrate();update();
